.TH FLICKCURL "1" "20 December 2007" "flickcurl-config" "User Commands"
.SH NAME
flickcurl-config \- script to get information about the installed version of flickcurl
.SH SYNOPSIS
.B flickcurl-config
[ \fIOPTION\fR ]
.SH DESCRIPTION
Known values for OPTION are:
.TP
\fB\-\-prefix\fR[=\fIDIR\fP]
Change flickcurl prefix (the default location is /usr).
.TP
\fB\-\-libs\fR
Print library linking information.
.TP
\fB\-\-libtool\-libs\fR
Print linking information for use with libtool.
.TP
\fB\-\-private\-libs\fR
Print library private/static linking information.
.TP
\fB\-\-cflags\fR
Print pre\-processor and compiler flags
.TP
\fB\-\-help\fR
display this help and exit
.TP
\fB\-\-version\fR
output version information
.TP
\fB\-\-version\-decimal\fR
Output version as a decimal integer.
.SH "AUTHOR"
This manual page was written by Kumar Appaiah <akumar@ee.iitm.ac.in>,
for the Debian project (but may be used by others).
