.TH FLICKCURL "1" "20 December 2007" "flickcurl-config" "User Commands"
.SH NAME
flickcurl-config \- script to get information about the installed version of flickcurl
.SH SYNOPSIS
.B flickcurl-config
[ \fIOPTION\fR ]
.SH DESCRIPTION
.IP
This program is \fBDEPRECATED\fP and pkg-config(1) should be used
to get flickcurl library parameters and dependencies.  The compiling
and linking flags are likely to not work since they do not import
dependendent libraries (such as Raptor).
.LP
Known values for OPTION are:
.TP
\fB\-\-prefix\fR
Get the flickcurl installation prefix.
.TP
\fB\-\-libs\fR
Print library linking information.
.TP
\fB\-\-private\-libs\fR
Print library private/static linking information.
.TP
\fB\-\-cflags\fR
Print pre\-processor and compiler flags
.TP
\fB\-\-help\fR
display this help and exit
.TP
\fB\-\-version\fR
output version information
.TP
\fB\-\-version\-decimal\fR
Output version as a decimal integer.
.SH "AUTHOR"
This manual page was written by Kumar Appaiah <akumar@ee.iitm.ac.in>,
for the Debian project (but may be used by others).
